name: Playwright + Allure → GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # 1) Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Node.js y dependencias
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci

      # 3) Instala navegadores de Playwright
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # 4) Corre los tests con Allure → ./allure-results
      - name: Run Playwright tests with Allure reporter
        run: npx playwright test 

      # 5) Instala Allure CLI
      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev

      # 6) Genera el sitio estático Allure
      - name: Generate Allure report
        run: |
          allure generate allure-results \
            --clean \
            -o allure-report

      # 7) Publica a gh‑pages
      - name: Publish Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token:       ${{ secrets.GITHUB_TOKEN }}
          publish_branch:     gh-pages
          publish_dir:        allure-report
          allow_empty_commit: true

