name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Instala Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # 3. Instalamos dependencias
      - name: Install dependencies
        run: npm ci

      # 4. Instalamos navegadores de Playwright
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # 5. Ejecuta tests con Allure → genera ./allure-results
      - name: Run Playwright tests with Allure reporter
        run: npx playwright test --reporter=list,allure-playwright

      # 6. DEBUG: listar archivos/carpetas para confirmar allure-results
      - name: Debug workspace
        if: always()
        run: |
          echo "=== Files in workspace ==="
          find . -maxdepth 2 -type f
          echo "=== Directories in workspace ==="
          find . -maxdepth 2 -type d

      # 7. Carga historial previo desde gh‑pages (no falla si aún no existe)
      - name: Load test report history
        if: always()
        continue-on-error: true
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token:      ${{ secrets.GITHUB_TOKEN }}
          ref:        gh-pages
          path:       allure-history

      # 8. Construye el reporte Allure (historial + resultados actuales)
      - name: Build Allure Report
        if: always()
        uses: simple-elf/allure-report-action@v1.12
        with:
          gh_pages:       allure-history      # carpeta con el historial
          allure_results: allure-results      # carpeta generada por Playwright
          allure_history: allure-report       # carpeta donde vuelca el HTML

      # 9. Publica en gh‑pages para GitHub Pages
      - name: Publish to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token:       ${{ secrets.GITHUB_TOKEN }}
          publish_branch:     gh-pages
          publish_dir:        allure-report
          allow_empty_commit: true





